// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v3.19.1
// source: logpilot.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "logpilot";

export interface LogRequest {
  channel: string;
  level: string;
  message: string;
  meta: { [key: string]: string };
  storage: string;
}

export interface LogRequest_MetaEntry {
  key: string;
  value: string;
}

export interface LogResponse {
  status: string;
  message: string;
}

/** LogPilot extension for batch processing */
export interface SendLogsRequest {
  logRequests: LogRequest[];
}

export interface SendLogsResponse {
  status: string;
  message: string;
}

export interface ListLogsRequest {
  storage: string;
  channel: string;
  level: string;
  fromTimestamp: number;
  toTimestamp: number;
}

export interface ListLogsResponse {
  logs: LogEntry[];
}

export interface FetchLogsRequest {
  since: string;
  channel: string;
  limit: number;
  storage: string;
}

export interface FetchLogsResponse {
  logs: LogEntry[];
}

export interface SeekRequest {
  channel: string;
  consumerId: string;
  /** EARLIEST, LATEST, SPECIFIC */
  operation: string;
  /** Only for SPECIFIC */
  logId: number;
  storage: string;
}

export interface SeekResponse {
  status: string;
  message: string;
}

export interface LogEntry {
  channel: string;
  level: string;
  message: string;
  meta: { [key: string]: string };
  timestamp: number;
  id: number;
}

export interface LogEntry_MetaEntry {
  key: string;
  value: string;
}

function createBaseLogRequest(): LogRequest {
  return { channel: "", level: "", message: "", meta: {}, storage: "" };
}

export const LogRequest: MessageFns<LogRequest> = {
  encode(message: LogRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.channel !== "") {
      writer.uint32(10).string(message.channel);
    }
    if (message.level !== "") {
      writer.uint32(18).string(message.level);
    }
    if (message.message !== "") {
      writer.uint32(26).string(message.message);
    }
    Object.entries(message.meta).forEach(([key, value]) => {
      LogRequest_MetaEntry.encode({ key: key as any, value }, writer.uint32(34).fork()).join();
    });
    if (message.storage !== "") {
      writer.uint32(42).string(message.storage);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LogRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLogRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.channel = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.level = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          const entry4 = LogRequest_MetaEntry.decode(reader, reader.uint32());
          if (entry4.value !== undefined) {
            message.meta[entry4.key] = entry4.value;
          }
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.storage = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LogRequest {
    return {
      channel: isSet(object.channel) ? globalThis.String(object.channel) : "",
      level: isSet(object.level) ? globalThis.String(object.level) : "",
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      meta: isObject(object.meta)
        ? Object.entries(object.meta).reduce<{ [key: string]: string }>((acc, [key, value]) => {
          acc[key] = String(value);
          return acc;
        }, {})
        : {},
      storage: isSet(object.storage) ? globalThis.String(object.storage) : "",
    };
  },

  toJSON(message: LogRequest): unknown {
    const obj: any = {};
    if (message.channel !== "") {
      obj.channel = message.channel;
    }
    if (message.level !== "") {
      obj.level = message.level;
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.meta) {
      const entries = Object.entries(message.meta);
      if (entries.length > 0) {
        obj.meta = {};
        entries.forEach(([k, v]) => {
          obj.meta[k] = v;
        });
      }
    }
    if (message.storage !== "") {
      obj.storage = message.storage;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LogRequest>, I>>(base?: I): LogRequest {
    return LogRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LogRequest>, I>>(object: I): LogRequest {
    const message = createBaseLogRequest();
    message.channel = object.channel ?? "";
    message.level = object.level ?? "";
    message.message = object.message ?? "";
    message.meta = Object.entries(object.meta ?? {}).reduce<{ [key: string]: string }>((acc, [key, value]) => {
      if (value !== undefined) {
        acc[key] = globalThis.String(value);
      }
      return acc;
    }, {});
    message.storage = object.storage ?? "";
    return message;
  },
};

function createBaseLogRequest_MetaEntry(): LogRequest_MetaEntry {
  return { key: "", value: "" };
}

export const LogRequest_MetaEntry: MessageFns<LogRequest_MetaEntry> = {
  encode(message: LogRequest_MetaEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LogRequest_MetaEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLogRequest_MetaEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LogRequest_MetaEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: LogRequest_MetaEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LogRequest_MetaEntry>, I>>(base?: I): LogRequest_MetaEntry {
    return LogRequest_MetaEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LogRequest_MetaEntry>, I>>(object: I): LogRequest_MetaEntry {
    const message = createBaseLogRequest_MetaEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseLogResponse(): LogResponse {
  return { status: "", message: "" };
}

export const LogResponse: MessageFns<LogResponse> = {
  encode(message: LogResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LogResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLogResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LogResponse {
    return {
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      message: isSet(object.message) ? globalThis.String(object.message) : "",
    };
  },

  toJSON(message: LogResponse): unknown {
    const obj: any = {};
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LogResponse>, I>>(base?: I): LogResponse {
    return LogResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LogResponse>, I>>(object: I): LogResponse {
    const message = createBaseLogResponse();
    message.status = object.status ?? "";
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseSendLogsRequest(): SendLogsRequest {
  return { logRequests: [] };
}

export const SendLogsRequest: MessageFns<SendLogsRequest> = {
  encode(message: SendLogsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.logRequests) {
      LogRequest.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SendLogsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSendLogsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.logRequests.push(LogRequest.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SendLogsRequest {
    return {
      logRequests: globalThis.Array.isArray(object?.logRequests)
        ? object.logRequests.map((e: any) => LogRequest.fromJSON(e))
        : [],
    };
  },

  toJSON(message: SendLogsRequest): unknown {
    const obj: any = {};
    if (message.logRequests?.length) {
      obj.logRequests = message.logRequests.map((e) => LogRequest.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SendLogsRequest>, I>>(base?: I): SendLogsRequest {
    return SendLogsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SendLogsRequest>, I>>(object: I): SendLogsRequest {
    const message = createBaseSendLogsRequest();
    message.logRequests = object.logRequests?.map((e) => LogRequest.fromPartial(e)) || [];
    return message;
  },
};

function createBaseSendLogsResponse(): SendLogsResponse {
  return { status: "", message: "" };
}

export const SendLogsResponse: MessageFns<SendLogsResponse> = {
  encode(message: SendLogsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SendLogsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSendLogsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SendLogsResponse {
    return {
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      message: isSet(object.message) ? globalThis.String(object.message) : "",
    };
  },

  toJSON(message: SendLogsResponse): unknown {
    const obj: any = {};
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SendLogsResponse>, I>>(base?: I): SendLogsResponse {
    return SendLogsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SendLogsResponse>, I>>(object: I): SendLogsResponse {
    const message = createBaseSendLogsResponse();
    message.status = object.status ?? "";
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseListLogsRequest(): ListLogsRequest {
  return { storage: "", channel: "", level: "", fromTimestamp: 0, toTimestamp: 0 };
}

export const ListLogsRequest: MessageFns<ListLogsRequest> = {
  encode(message: ListLogsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.storage !== "") {
      writer.uint32(10).string(message.storage);
    }
    if (message.channel !== "") {
      writer.uint32(18).string(message.channel);
    }
    if (message.level !== "") {
      writer.uint32(26).string(message.level);
    }
    if (message.fromTimestamp !== 0) {
      writer.uint32(32).int64(message.fromTimestamp);
    }
    if (message.toTimestamp !== 0) {
      writer.uint32(40).int64(message.toTimestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListLogsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListLogsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.storage = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.channel = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.level = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.fromTimestamp = longToNumber(reader.int64());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.toTimestamp = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListLogsRequest {
    return {
      storage: isSet(object.storage) ? globalThis.String(object.storage) : "",
      channel: isSet(object.channel) ? globalThis.String(object.channel) : "",
      level: isSet(object.level) ? globalThis.String(object.level) : "",
      fromTimestamp: isSet(object.fromTimestamp) ? globalThis.Number(object.fromTimestamp) : 0,
      toTimestamp: isSet(object.toTimestamp) ? globalThis.Number(object.toTimestamp) : 0,
    };
  },

  toJSON(message: ListLogsRequest): unknown {
    const obj: any = {};
    if (message.storage !== "") {
      obj.storage = message.storage;
    }
    if (message.channel !== "") {
      obj.channel = message.channel;
    }
    if (message.level !== "") {
      obj.level = message.level;
    }
    if (message.fromTimestamp !== 0) {
      obj.fromTimestamp = Math.round(message.fromTimestamp);
    }
    if (message.toTimestamp !== 0) {
      obj.toTimestamp = Math.round(message.toTimestamp);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListLogsRequest>, I>>(base?: I): ListLogsRequest {
    return ListLogsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListLogsRequest>, I>>(object: I): ListLogsRequest {
    const message = createBaseListLogsRequest();
    message.storage = object.storage ?? "";
    message.channel = object.channel ?? "";
    message.level = object.level ?? "";
    message.fromTimestamp = object.fromTimestamp ?? 0;
    message.toTimestamp = object.toTimestamp ?? 0;
    return message;
  },
};

function createBaseListLogsResponse(): ListLogsResponse {
  return { logs: [] };
}

export const ListLogsResponse: MessageFns<ListLogsResponse> = {
  encode(message: ListLogsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.logs) {
      LogEntry.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListLogsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListLogsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.logs.push(LogEntry.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListLogsResponse {
    return { logs: globalThis.Array.isArray(object?.logs) ? object.logs.map((e: any) => LogEntry.fromJSON(e)) : [] };
  },

  toJSON(message: ListLogsResponse): unknown {
    const obj: any = {};
    if (message.logs?.length) {
      obj.logs = message.logs.map((e) => LogEntry.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListLogsResponse>, I>>(base?: I): ListLogsResponse {
    return ListLogsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListLogsResponse>, I>>(object: I): ListLogsResponse {
    const message = createBaseListLogsResponse();
    message.logs = object.logs?.map((e) => LogEntry.fromPartial(e)) || [];
    return message;
  },
};

function createBaseFetchLogsRequest(): FetchLogsRequest {
  return { since: "", channel: "", limit: 0, storage: "" };
}

export const FetchLogsRequest: MessageFns<FetchLogsRequest> = {
  encode(message: FetchLogsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.since !== "") {
      writer.uint32(10).string(message.since);
    }
    if (message.channel !== "") {
      writer.uint32(18).string(message.channel);
    }
    if (message.limit !== 0) {
      writer.uint32(24).int32(message.limit);
    }
    if (message.storage !== "") {
      writer.uint32(34).string(message.storage);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FetchLogsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFetchLogsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.since = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.channel = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.storage = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FetchLogsRequest {
    return {
      since: isSet(object.since) ? globalThis.String(object.since) : "",
      channel: isSet(object.channel) ? globalThis.String(object.channel) : "",
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : 0,
      storage: isSet(object.storage) ? globalThis.String(object.storage) : "",
    };
  },

  toJSON(message: FetchLogsRequest): unknown {
    const obj: any = {};
    if (message.since !== "") {
      obj.since = message.since;
    }
    if (message.channel !== "") {
      obj.channel = message.channel;
    }
    if (message.limit !== 0) {
      obj.limit = Math.round(message.limit);
    }
    if (message.storage !== "") {
      obj.storage = message.storage;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FetchLogsRequest>, I>>(base?: I): FetchLogsRequest {
    return FetchLogsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FetchLogsRequest>, I>>(object: I): FetchLogsRequest {
    const message = createBaseFetchLogsRequest();
    message.since = object.since ?? "";
    message.channel = object.channel ?? "";
    message.limit = object.limit ?? 0;
    message.storage = object.storage ?? "";
    return message;
  },
};

function createBaseFetchLogsResponse(): FetchLogsResponse {
  return { logs: [] };
}

export const FetchLogsResponse: MessageFns<FetchLogsResponse> = {
  encode(message: FetchLogsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.logs) {
      LogEntry.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FetchLogsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFetchLogsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.logs.push(LogEntry.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FetchLogsResponse {
    return { logs: globalThis.Array.isArray(object?.logs) ? object.logs.map((e: any) => LogEntry.fromJSON(e)) : [] };
  },

  toJSON(message: FetchLogsResponse): unknown {
    const obj: any = {};
    if (message.logs?.length) {
      obj.logs = message.logs.map((e) => LogEntry.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FetchLogsResponse>, I>>(base?: I): FetchLogsResponse {
    return FetchLogsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FetchLogsResponse>, I>>(object: I): FetchLogsResponse {
    const message = createBaseFetchLogsResponse();
    message.logs = object.logs?.map((e) => LogEntry.fromPartial(e)) || [];
    return message;
  },
};

function createBaseSeekRequest(): SeekRequest {
  return { channel: "", consumerId: "", operation: "", logId: 0, storage: "" };
}

export const SeekRequest: MessageFns<SeekRequest> = {
  encode(message: SeekRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.channel !== "") {
      writer.uint32(10).string(message.channel);
    }
    if (message.consumerId !== "") {
      writer.uint32(18).string(message.consumerId);
    }
    if (message.operation !== "") {
      writer.uint32(26).string(message.operation);
    }
    if (message.logId !== 0) {
      writer.uint32(32).int64(message.logId);
    }
    if (message.storage !== "") {
      writer.uint32(42).string(message.storage);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SeekRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSeekRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.channel = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.consumerId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.operation = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.logId = longToNumber(reader.int64());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.storage = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SeekRequest {
    return {
      channel: isSet(object.channel) ? globalThis.String(object.channel) : "",
      consumerId: isSet(object.consumerId) ? globalThis.String(object.consumerId) : "",
      operation: isSet(object.operation) ? globalThis.String(object.operation) : "",
      logId: isSet(object.logId) ? globalThis.Number(object.logId) : 0,
      storage: isSet(object.storage) ? globalThis.String(object.storage) : "",
    };
  },

  toJSON(message: SeekRequest): unknown {
    const obj: any = {};
    if (message.channel !== "") {
      obj.channel = message.channel;
    }
    if (message.consumerId !== "") {
      obj.consumerId = message.consumerId;
    }
    if (message.operation !== "") {
      obj.operation = message.operation;
    }
    if (message.logId !== 0) {
      obj.logId = Math.round(message.logId);
    }
    if (message.storage !== "") {
      obj.storage = message.storage;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SeekRequest>, I>>(base?: I): SeekRequest {
    return SeekRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SeekRequest>, I>>(object: I): SeekRequest {
    const message = createBaseSeekRequest();
    message.channel = object.channel ?? "";
    message.consumerId = object.consumerId ?? "";
    message.operation = object.operation ?? "";
    message.logId = object.logId ?? 0;
    message.storage = object.storage ?? "";
    return message;
  },
};

function createBaseSeekResponse(): SeekResponse {
  return { status: "", message: "" };
}

export const SeekResponse: MessageFns<SeekResponse> = {
  encode(message: SeekResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SeekResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSeekResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SeekResponse {
    return {
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      message: isSet(object.message) ? globalThis.String(object.message) : "",
    };
  },

  toJSON(message: SeekResponse): unknown {
    const obj: any = {};
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SeekResponse>, I>>(base?: I): SeekResponse {
    return SeekResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SeekResponse>, I>>(object: I): SeekResponse {
    const message = createBaseSeekResponse();
    message.status = object.status ?? "";
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseLogEntry(): LogEntry {
  return { channel: "", level: "", message: "", meta: {}, timestamp: 0, id: 0 };
}

export const LogEntry: MessageFns<LogEntry> = {
  encode(message: LogEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.channel !== "") {
      writer.uint32(10).string(message.channel);
    }
    if (message.level !== "") {
      writer.uint32(18).string(message.level);
    }
    if (message.message !== "") {
      writer.uint32(26).string(message.message);
    }
    Object.entries(message.meta).forEach(([key, value]) => {
      LogEntry_MetaEntry.encode({ key: key as any, value }, writer.uint32(34).fork()).join();
    });
    if (message.timestamp !== 0) {
      writer.uint32(40).int64(message.timestamp);
    }
    if (message.id !== 0) {
      writer.uint32(48).int64(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LogEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLogEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.channel = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.level = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          const entry4 = LogEntry_MetaEntry.decode(reader, reader.uint32());
          if (entry4.value !== undefined) {
            message.meta[entry4.key] = entry4.value;
          }
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.timestamp = longToNumber(reader.int64());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LogEntry {
    return {
      channel: isSet(object.channel) ? globalThis.String(object.channel) : "",
      level: isSet(object.level) ? globalThis.String(object.level) : "",
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      meta: isObject(object.meta)
        ? Object.entries(object.meta).reduce<{ [key: string]: string }>((acc, [key, value]) => {
          acc[key] = String(value);
          return acc;
        }, {})
        : {},
      timestamp: isSet(object.timestamp) ? globalThis.Number(object.timestamp) : 0,
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
    };
  },

  toJSON(message: LogEntry): unknown {
    const obj: any = {};
    if (message.channel !== "") {
      obj.channel = message.channel;
    }
    if (message.level !== "") {
      obj.level = message.level;
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.meta) {
      const entries = Object.entries(message.meta);
      if (entries.length > 0) {
        obj.meta = {};
        entries.forEach(([k, v]) => {
          obj.meta[k] = v;
        });
      }
    }
    if (message.timestamp !== 0) {
      obj.timestamp = Math.round(message.timestamp);
    }
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LogEntry>, I>>(base?: I): LogEntry {
    return LogEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LogEntry>, I>>(object: I): LogEntry {
    const message = createBaseLogEntry();
    message.channel = object.channel ?? "";
    message.level = object.level ?? "";
    message.message = object.message ?? "";
    message.meta = Object.entries(object.meta ?? {}).reduce<{ [key: string]: string }>((acc, [key, value]) => {
      if (value !== undefined) {
        acc[key] = globalThis.String(value);
      }
      return acc;
    }, {});
    message.timestamp = object.timestamp ?? 0;
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseLogEntry_MetaEntry(): LogEntry_MetaEntry {
  return { key: "", value: "" };
}

export const LogEntry_MetaEntry: MessageFns<LogEntry_MetaEntry> = {
  encode(message: LogEntry_MetaEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LogEntry_MetaEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLogEntry_MetaEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LogEntry_MetaEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: LogEntry_MetaEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LogEntry_MetaEntry>, I>>(base?: I): LogEntry_MetaEntry {
    return LogEntry_MetaEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LogEntry_MetaEntry>, I>>(object: I): LogEntry_MetaEntry {
    const message = createBaseLogEntry_MetaEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

export interface LogService {
  SendLog(request: LogRequest): Promise<LogResponse>;
  /** LogPilot extension */
  SendLogs(request: SendLogsRequest): Promise<SendLogsResponse>;
  ListLogs(request: ListLogsRequest): Promise<ListLogsResponse>;
  FetchLogs(request: FetchLogsRequest): Promise<FetchLogsResponse>;
  Seek(request: SeekRequest): Promise<SeekResponse>;
}

export const LogServiceServiceName = "logpilot.LogService";
export class LogServiceClientImpl implements LogService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || LogServiceServiceName;
    this.rpc = rpc;
    this.SendLog = this.SendLog.bind(this);
    this.SendLogs = this.SendLogs.bind(this);
    this.ListLogs = this.ListLogs.bind(this);
    this.FetchLogs = this.FetchLogs.bind(this);
    this.Seek = this.Seek.bind(this);
  }
  SendLog(request: LogRequest): Promise<LogResponse> {
    const data = LogRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "SendLog", data);
    return promise.then((data) => LogResponse.decode(new BinaryReader(data)));
  }

  SendLogs(request: SendLogsRequest): Promise<SendLogsResponse> {
    const data = SendLogsRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "SendLogs", data);
    return promise.then((data) => SendLogsResponse.decode(new BinaryReader(data)));
  }

  ListLogs(request: ListLogsRequest): Promise<ListLogsResponse> {
    const data = ListLogsRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "ListLogs", data);
    return promise.then((data) => ListLogsResponse.decode(new BinaryReader(data)));
  }

  FetchLogs(request: FetchLogsRequest): Promise<FetchLogsResponse> {
    const data = FetchLogsRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "FetchLogs", data);
    return promise.then((data) => FetchLogsResponse.decode(new BinaryReader(data)));
  }

  Seek(request: SeekRequest): Promise<SeekResponse> {
    const data = SeekRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "Seek", data);
    return promise.then((data) => SeekResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
